### PR TITLE
Leuven GPGPU

### LINKED ISSUE #301: [UGent] How to access Leuven GPGPU system?
http://hpc.ugent.be/userwiki/index.php/Tips:Software:GPGPU

### PR DESCRIPTION
**Pull request by redfast00**
Fixes #301

### CODE REVIEW

**Comment by redfast00** [comment]
@boegel maybe also ask people from Leuven if this still works? Couldn't test it since I'm not in that group.

**Comment by redfast00** [comment]
While on the topic of Leuven, I added their installation form as well.

**Comment by boegel** [comment]
@mselwa Can you verify whether this information is still accurate for non-KUL VSC users?

**Comment by boegel** [comment]
@mselwa ping?

**Comment by mselwa** [comment]
It is certainly outdated. Sorry - I will need more time. Now teaching seazon has started for me and I am busy with our MOOC. 
I was hoping to re-write the info when the new website is there.
If you do not want to wait a couple of weeks - you can adjust your Gent website - phis and M2070 are gone.

For new Genius nodes - I am not sure how the users from UGent can use it.

**Comment by mselwa** [comment]
I just got the new info from Jan. 

The current project lp_GPU_GENT will work only till we put Genius in production (18 October).  Since then - all the users should follow the same procedure - i.e. purchase credits from https://icts.kuleuven.be/sc/forms/Aanvraagformulier_HPC_Credits, extra info about prices https://icts.kuleuven.be/sc/onderzoeksgegevens/HPC. 

The lp_GPU_GENT was given for k20 use only and those old nodes are at end of life time.

**Comment by boegel** [comment]
@mselwa Thank you for clarifying.

Both the links you provided require logging in with a KUL account though...

Is there an alternative on a public page somewhere?

**Comment by boegel** [comment]
> @mselwa Thank you for clarifying.
> 
> Both the links you provided require logging in with a KUL account though...
> 
> Is there an alternative on a public page somewhere?

@mselwa ping? ^

**Comment by boegel** [comment]
No longer relevant, see #358

**Pull request closed without merging**
