### PR TITLE
Replace images in web_portal.md and jupyter.md due to new web portal

### LINKED ISSUE #703: Update screenshots in web_portal.md and jupyter.md for new web portal version
the HPC-UGent web portal will be updated to a new version.
Look and feel is mostly the same, but there are some small differences, so some screenshots currently in the docs at https://docs.hpc.ugent.be/web_portal/ + https://docs.hpc.ugent.be/jupyter/ should be updated.

Preview of new web portal is available via https://shieldon.ugent.be/qaood.

### PR DESCRIPTION
**Pull request by lbarraga**
closes #703 

- `web_portal.md`
  - `ood_start.png`: small changes in look. The original also did not render the logo correctly
  - `ood_hamburger.png`: menu  is now centered
  - `ood_lanch_desktop.png`: the victini cluster no longer exists, side panel is also updated
  - `ood_desktop_running.png`: victini is no longer exists
  - `ood_file_explorer`: new look and feel
- `jupyter.md`
  - `ood_jupyter_open_shell.md`: now has two entries: RHEL8 and RHEL9. I renamed this to `ood_open_shell.png`

The rest of the images did not need to be renewed in my opinion as visual changes were very minimal.

### CODE REVIEW

**Review by boegel — CHANGES_REQUESTED** [review]
@lbarraga 
* Can you see if you can get rid of these "course" entry in left menu in file browser screenshot? Photoshop it if that's easier.
* The "login shell access" screenshot looks wrong, there's only an `EL8/`EL9` option, your screenshot shows three entries (and I'm hoping these can still be renamed to `RHEL8` and `RHEL9`, ping @stdweird ?)

**Comment by stdweird** [comment]
@boegel i thought wouter fixed those?

**Comment by stdweird** [comment]
@lbarraga maybe rename the open shell screenshots (they have nothing to do with juypiter); and make screenhots from qaood (there should only be RHEL8/RHEL9 entries)

**Comment by stdweird** [comment]
@boegel @lbarraga  wrt the courses, you must be in a course group to see this. we can kick lukas out of it, so he can make clean screeshots (or just mention, that you might get this when part of a course (and link to the course docs)

**Comment by lbarraga** [comment]
@stdweird now that you mention it, some screenshots indeed might not have been taken on qaood. I will recheck. 
No need to remove me from a course, I think I can delete the entry using inspect element.

**Comment by boegel** [comment]
> @boegel i thought wouter fixed those?

Maybe not deployed yet, I still see `EL8` instead of `RHEL8` on QA setup of OoD

**Comment by lbarraga** [comment]
@boegel @stdweird I have updated the `ood_file_explorer.png` image to not contain the course. I also made it a little bit bigger. I took a new screen shot of the open shell panel, which now only contains 2 entries, and renamed it to `ood_open_shell.png`

**Review by boegel — APPROVED** [review]

**Pull request merged**
