### PR TITLE
made all listings minipages, so they don't get split over multiple pages

### PR DESCRIPTION
**Pull request by JensTimmerman**

### CODE REVIEW

**Comment by boegel** [comment]
Looks good to m. Maybe @gjbex can take a look at this before we merge it in?

**Comment by itkovian** [comment]
Then assign it to him, @boegel?

**Comment by boegel** [comment]
@itkovian: OK, but I don't think assigning results in a notification in his inbox...

anyway: @gjbex: assigning this to you

**Comment by boegel** [comment]
ah, ok, assigning to @gjbex doesn't work, you can only assign to admins of the repo...

**Pull request merged**
