### PR TITLE
Apt latex

### PR DESCRIPTION
**Pull request by JensTimmerman**

### CODE REVIEW

**Comment by JensTimmerman** [comment]
@wpoely86 this looks a lot faster? ` Duration: 5 min 53 sec`

**Comment by wpoely86** [comment]
Did you check the rendered pdf's? When I set this up, the LaTeX available in travis was ancient and I had to manually install it to get a recent version.

If it works, fine by me to switch to this.

**Comment by JensTimmerman** [comment]
any pointers on how I can check the rendered pdfs?

**Comment by wpoely86** [comment]
Have a quick look yourself is probably the easiest. Extracting all pages and diffing before and after is the full blown solution.

But if anything about the rendering goes horrible wrong, it should be quite easy to spot.

**Comment by JensTimmerman** [comment]
but how do I get access to the pdf's built for this branch?
I should add an extra repo and push to it?

**Comment by wpoely86** [comment]
a yes. An extra repo could work.

Or push to the master branch your own repo. I think you can 'overwrite' the environment variables in the travis file by setting it directly in travis for your own repo. Just change the repo to your own and add a key to push to it.

**Comment by JensTimmerman** [comment]
we should retry on the 'latest' travis images, 
https://blog.travis-ci.com/2017-12-01-new-update-schedule-for-linux-build-images

**Comment by boegel** [comment]
@JensTimmerman Is this still relevant?

**Pull request closed without merging**
