### PR TITLE
Datadocs

### PR DESCRIPTION
**Pull request by tdanckaert**
This can serve as a starting point for the VSC storage platform documentation.

### CODE REVIEW

**Comment by wdpypere** [comment]
@tdanckaert this PR seems to have conflicts. Can you have a look at it?

**Comment by tdanckaert** [comment]
Hi,

I was asked to create a skeleton that could serve as a starting point for the documentation of the data service, to be written by someone else, and to submit that as a pull request.  That was one year ago, I don't know if it's still relevant (I don't work at VSC anymore).  Probably the pull request can be closed (if not, the conflict is quite simple)...

**Comment by wdpypere** [comment]
thanks for getting back at this @tdanckaert . I resolved the conflict. @stdweird do we want this skeleton merged?

**Comment by wdpypere** [comment]
@stdweird or do you want me to reopen https://github.com/hpcugent/vsc_user_docs/pull/347 ?

**Comment by stdweird** [comment]
@tdanckaert @wdpypere i think it was decided to move the globus docs to the regular/other vsc docs
you can close tihs for now, if ever needed, we can reopen it

**Pull request closed without merging**
