### PR TITLE
[WIP] Quota

### PR DESCRIPTION
**Pull request by redfast00**
See  #177

### CODE REVIEW

**Comment by redfast00** [comment]
Yes, and the information for Antwerpen doesn't seem to be correct: if I SSH to there, it doesn't display any quota. But then again, it also doesn't work in Leuven, and I don't know what it is in VUB, but if it's `quota -s`, it gives the same error as in Leuven.

I think quota for non-local users might indeed be broken.

**Comment by boegel** [comment]
for VUB: @wpoely86

**Comment by boegel** [comment]
@smoors, @wpoely86: how can VUB users check their quota usage?

**Comment by smoors** [comment]
@boegel quota can be checked with the command `myquota`.

**Comment by smoors** [comment]
it gives a summary of the quota on $VSC_HOME and $VSC_SCRATCH.

**Pull request merged**
