### PR TITLE
Make navigating easier by coloring links blue

### PR DESCRIPTION
**Pull request by redfast00**

### CODE REVIEW

**Comment by boegel** [comment]
@redfast00 Can you include a screenshot to show how it looks before & after?

**Comment by redfast00** [comment]
screen See the blue text in the window on the left? That's how it looks after. Now imagine it's black, that's the before.

**Comment by boegel** [comment]
@redfast00 Would underlining as well make sense, you think? Like people are used to on websites (maybe I'm still stuck in the 90s though).

**Comment by redfast00** [comment]
This is "hard", are regular blue links fine?

**Comment by boegel** [comment]
Underlined links are probably ugly too, so let's go forward with this as is...

**Pull request merged**
