### PR TITLE
Even less packages

### PR DESCRIPTION
**Pull request by redfast00**

### CODE REVIEW

**Comment by redfast00** [comment]
Correct. I'll add in a patch to drop the cache, and remove it as last commit of this PR

**Comment by boegel** [comment]
:+1:

**Comment by sbecuwe** [comment]
No, ConTeXt is not needed for the tutorial.

**Comment by redfast00** [comment]
@sbecuwe we want to trim the texlive install down, so Travis has enough time to install + build everything. Do you know some more things we can remove?

**Comment by boegel** [comment]
@redfast00 Last test on Travis took < 30m (without cache), so trimming things down seems to be helping...

**Comment by sbecuwe** [comment]
It seems latexmk is part of collection-binextra. Sorry!

**Comment by sbecuwe** [comment]
strange: tracklang.sty would be part of collection-plaingeneric, but that is not mentioned in texlive.profile ...
Contents of the different collections can be found in http://mirror.ctan.org/systems/texlive/tlnet/tlpkg/texlive.tlpdb

**Comment by redfast00** [comment]
That URL is really useful! Turns out collection-pstricks depends on collection-plaingeneric.

**Comment by redfast00** [comment]
11 minutes for a full install and compile (so only 5 minutes to install)! I haven't checked if the PDF's look exactly the same, but I'm hopeful.

**Comment by redfast00** [comment]
Please note that this hasn't been tested: it's possible the PDF's look really ugly or are rendered incorrectly: all we know is that they successfully compile, but that's it. If this is merged into master, it would be a good idea to check the pdf's they produced.

**Comment by boegel** [comment]
I'm merging this, I'll take a look at the resulting PDFs and revert these changes if I notice any serious issues...

**Comment by boegel** [comment]
I didn't see any major issues in the resulting PDFs :+1:

**Pull request merged**
