### PR TITLE
Uantwerpen 2017.10 02

### PR DESCRIPTION
**Pull request by klust**
Work by Kurt and Stefan: Removed references to turing and added information about leibniz, our new cluster (so mostly UAntwerp-only text). I also corrected an error in the text about the monitor command in the fine tuning of job specifications sections, which is used in all versions of the tutorial except the UGent versions.

### CODE REVIEW

**Comment by wpoely86** [comment]
Close/Reopen to trigger travis?

**Comment by boegel** [comment]
There were some problems with Travis earlier, see https://www.traviscistatus.com/ .

Let's try again...

**Comment by boegel** [comment]
Hmm, for some reason Travis still isn't picking up on this... :-/

**Comment by boegel** [comment]
@klust Can you try closing this PR and opening a new one, so Travis runs the tests for your changes?

**Comment by klust** [comment]
As requested...

**Pull request closed without merging**
