### PR TITLE
Uantwerpen 2017.10 02

### PR DESCRIPTION
**Pull request by klust**
As requested, another try...

### CODE REVIEW

**Comment by boegel** [comment]
So, Travis isn't picking up on this, again... Any ideas @wpoely86?

**Comment by boegel** [comment]
OK, so Travis still isn't picking this up.

I've seen this happen before, the reason turned out to be that the person issuing the PR got blacklisted somehow by Travis. @wpoely86 may have more info.

@klust Maybe try reaching out to Travis support on this, I think it's important we sort this out...

To bypass it, someone else can issue the PR using your branch, that may be sufficient.

**Comment by klust** [comment]
I'll try to reopen once more, as I've signed out and signed in again from Travis in case there would have been problems with the connection to my account.

**Comment by klust** [comment]
And now the build starts...

**Comment by boegel** [comment]
OK, that's weird, because the build isn't started under your Travis account, but under the `hpcugent` one.

Anyway, good to see it's fixed! :)

**Comment by klust** [comment]
Yes it is weird because Stefan said me he didn't remember ever having opened such an account while a few weeks ago it did work for him.

**Comment by boegel** [comment]
Fully reviewed, lgtm, Travis is happy, so merging. Thanks @klust!

**Pull request merged**
